### PR TITLE
Jic css

### PR DESCRIPTION
**Pull request by jicarter**
add background color
add text color
add heading color
centered content
added borders

### CODE REVIEW

**Comment by Chris-Denmark** [comment]
You'll want to add a class to the h2 elements and style them to be center aligned.

**Comment by cslunetta** [comment]
I'm ok with pushing this through for now. Might need additional styling but we can tweak it after.

**Comment by lcurtis4** [comment]
👍

**Comment by Chris-Denmark** [comment]
👍

**Pull request merged**
